2025-01-20 13:38:20,041 INFO    MainThread:131440 [wandb_setup.py:_flush():68] Current SDK version is 0.19.4
2025-01-20 13:38:20,041 INFO    MainThread:131440 [wandb_setup.py:_flush():68] Configure stats pid to 131440
2025-01-20 13:38:20,042 INFO    MainThread:131440 [wandb_setup.py:_flush():68] Loading settings from /home/nils/.config/wandb/settings
2025-01-20 13:38:20,042 INFO    MainThread:131440 [wandb_setup.py:_flush():68] Loading settings from /home/nils/Documents/repositories/2024-25b-fai2-adsai-NilsVos234051/robotics_tasks/wandb/settings
2025-01-20 13:38:20,042 INFO    MainThread:131440 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-01-20 13:38:20,042 INFO    MainThread:131440 [wandb_init.py:setup_run_log_directory():624] Logging user logs to /home/nils/Documents/repositories/2024-25b-fai2-adsai-NilsVos234051/robotics_tasks/wandb/run-20250120_133820-tybircq3/logs/debug.log
2025-01-20 13:38:20,042 INFO    MainThread:131440 [wandb_init.py:setup_run_log_directory():625] Logging internal logs to /home/nils/Documents/repositories/2024-25b-fai2-adsai-NilsVos234051/robotics_tasks/wandb/run-20250120_133820-tybircq3/logs/debug-internal.log
2025-01-20 13:38:20,042 INFO    MainThread:131440 [wandb_init.py:init():743] calling init triggers
2025-01-20 13:38:20,042 INFO    MainThread:131440 [wandb_init.py:init():748] wandb.init called with sweep_config: {}
config: {}
2025-01-20 13:38:20,042 INFO    MainThread:131440 [wandb_init.py:init():776] starting backend
2025-01-20 13:38:20,268 INFO    MainThread:131440 [wandb_init.py:init():780] sending inform_init request
2025-01-20 13:38:20,287 INFO    MainThread:131440 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-01-20 13:38:20,288 INFO    MainThread:131440 [wandb_init.py:init():795] backend started and connected
2025-01-20 13:38:20,290 INFO    MainThread:131440 [wandb_init.py:init():888] updated telemetry
2025-01-20 13:38:20,305 INFO    MainThread:131440 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-01-20 13:38:20,574 ERROR   MainThread:131440 [wandb_init.py:init():944] encountered error: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2025-01-20 13:38:20,575 ERROR   MainThread:131440 [wandb_init.py:init():1454] error in wandb.init()
Traceback (most recent call last):
  File "/home/nils/anaconda3/envs/blockB/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1444, in init
    return wi.init(run_settings, run_config)
  File "/home/nils/anaconda3/envs/blockB/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 950, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2025-01-20 13:38:20,586 WARNING MsgRouterThr:131440 [router.py:message_loop():75] message_loop has been closed
